In [1]:
import numpy as np

In [3]:
def Ex1():
    A=np.arange(21)
    A[9:16]=A[9:16]*(-1)
    return (A)
print(Ex1())

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [42]:
def Ex2():
    A=np.arange(15,56)
    print(A[1:-1])
    return A
Ex2()

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [6]:
def Ex4():
    A=np.linspace(5,50,10)
    return A
print(Ex4())

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [7]:
def Ex5():
    A=np.random.randint(0, 11, size=5)
    return A
print(Ex5())

[5 0 9 7 7]


In [9]:
def Ex6(A,B):
    return A*B
print(Ex6(Ex5(),Ex5()))

[ 8 32  2  8 20]


In [11]:
def Ex7():
    A= np.arange(10,22).reshape(3,4)
    return A
print(Ex7())

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [12]:
def Ex8(A):
    return A.shape
print(Ex8(Ex7()))

(3, 4)


In [41]:
def Ex9():
    A=np.zeros((4,4),dtype=int)
    for i in range(4):
        for j in range(4):
            if (i+j)%2!=0:
                A[i,j]=1
    return A
print(Ex9())

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [14]:
def Ex10(A,B):
    print(A)
    print(B)
    return np.intersect1d(A,B)
print(Ex10(Ex5(),Ex5()))

[ 6  0  3 10  6]
[1 9 6 4 9]
[6]


In [15]:
def Ex11(A):
    print(A)
    return np.unique(A)
print(Ex11(Ex5()))

[3 7 5 0 8]
[0 3 5 7 8]


In [21]:
def Ex12():
    A=np.array([1, 2, 3])
    B= np.array([4, 5, 6])
    return np.cross(A,B)
print(Ex12())

[-3  6 -3]


In [22]:
def Ex13():
    return A

In [25]:
def Ex14(A,B):
    print(A)
    print(B)
    C= np.abs(A-B)
    return A[np.argmin(C)]
print(Ex14(Ex5(),7.9))

[6 0 1 5 4]
7.9
6
